#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define TASK_STATE 0 /* offsetof(struct task_struct, state)	# */
#define TASK_FLAGS 12 /* offsetof(struct task_struct, flags)	# */
#define TASK_PTRACE 16 /* offsetof(struct task_struct, ptrace)	# */
#define TASK_THREAD 428 /* offsetof(struct task_struct, thread)	# */
#define TASK_MM 132 /* offsetof(struct task_struct, mm)	# */
#define TASK_ACTIVE_MM 136 /* offsetof(struct task_struct, active_mm)	# */
#define TI_TASK 0 /* offsetof(struct thread_info, task)	# */
#define TI_EXEC_DOMAIN 4 /* offsetof(struct thread_info, exec_domain)	# */
#define TI_FLAGS 8 /* offsetof(struct thread_info, flags)	# */
#define TI_CPU 12 /* offsetof(struct thread_info, cpu)	# */
#define TI_PREEMPT 16 /* offsetof(struct thread_info, preempt_count)	# */
#define TI_ADDR_LIMIT 20 /* offsetof(struct thread_info, addr_limit)	# */
#define TI_RESTART_BLOCK 24 /* offsetof(struct thread_info, restart_block)	# */
#define TI_KSP 44 /* offsetof(struct thread_info, ksp)	# */
#define STACK_FRAME_OVERHEAD 128 /* STACK_FRAME_OVERHEAD	# */
#define INT_FRAME_SIZE 272 /* STACK_FRAME_OVERHEAD + sizeof(struct pt_regs)	# */
#define NUM_USER_SEGMENTS 8 /* TASK_SIZE>>28	# */

#endif
